### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by safooray** [Piyushi-0/ACE#1]
Question: In the MNIST notebook, what is the purpose of the sigmoid function applied to the decoder output? Is it just to bring the generated output within a visualizable range?

Thank you for publishing your code. I am hoping to use your attribution ideas in my problem domain.

**Comment by Piyushi-0** [comment]
Thank you for writing to us and showing interest in our work.
We use Bernoulli to model MNIST & so, given an input x and the latent z, we can interpret the output of decoder after applying sigmoid to it, as E[x|z]. As described in A.6.2 in our [paper](https://arxiv.org/pdf/1902.02302.pdf), we use iterated expectations E_z [E_x [x|do(z)]] to compute baseline. After intervening the latent, we get the inner expectation's value from the decoder's output. For brevity, here, I only used z to represent the latent & did not mention c & z separately. The details are in the paper. 
Please let us know if you have any more queries. Apologies for the late reply. The responses will be quicker from the next time.
